[package]
name = "bio"
version = "0.1.0"
authors = ["George Roubos <cowkingdom@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "bio"
path = "src/lib.rs"

[dependencies]

[dev-dependencies]
cargo-husky = "1.5"

[[bin]]
name = "dna"
path = "bin/dna.rs"

[[bin]]
name = "rna"
path = "bin/rna.rs"

[[bin]]
name = "revc"
path = "bin/revc.rs"

[[bin]]
name = "fib"
path = "bin/fib.rs"

[[bin]]
name = "iprb"
path = "bin/iprb.rs"

[[bin]]
name = "gc"
path = "bin/gc.rs"

[[bin]]
name = "grph"
path = "bin/grph.rs"

[[bin]]
name = "prot"
path = "bin/prot.rs"

[[bin]]
name = "ham"
path = "bin/ham.rs"

[[bin]]
name = "subs"
path = "bin/subs.rs"