[package]
name = "bio"
version = "0.1.0"
authors = ["George Roubos <cowkingdom@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "bio"
path = "src/lib.rs"
doctest = false

[dependencies]

[dev-dependencies]
cargo-husky = "1.5"
criterion = "0.3"

[[bench]]
name = "seq"
harness = false

[[bin]]
name = "dna"
path = "bin/dna.rs"
doctest = false
test = false

[[bin]]
name = "rna"
path = "bin/rna.rs"
test = false
doctest = false

[[bin]]
name = "revc"
path = "bin/revc.rs"
test = false
doctest = false

[[bin]]
name = "fib"
path = "bin/fib.rs"
test = false
doctest = false

[[bin]]
name = "iprb"
path = "bin/iprb.rs"
test = false
doctest = false

[[bin]]
name = "gc"
path = "bin/gc.rs"
test = false
doctest = false

[[bin]]
name = "grph"
path = "bin/grph.rs"
test = false
doctest = false

[[bin]]
name = "prot"
path = "bin/prot.rs"
test = false
doctest = false

[[bin]]
name = "ham"
path = "bin/ham.rs"
test = false
doctest = false

[[bin]]
name = "subs"
path = "bin/subs.rs"
test = false
doctest = false

[[bin]]
name = "revp"
path = "bin/revp.rs"
test = false
doctest = false

[[bin]]
name = "orf"
path = "bin/orf.rs"
test = false
doctest = false

[[bin]]
name = "mrna"
path = "bin/mrna.rs"
test = false
doctest = false

[[bin]]
name = "perm"
path = "bin/perm.rs"
test = false
doctest = false

[[bin]]
name = "pper"
path = "bin/pper.rs"
test = false
doctest = false

[[bin]]
name = "splc"
path = "bin/splc.rs"
test = false
doctest = false

[[bin]]
name = "lexf"
path = "bin/lexf.rs"
test = false
doctest = false