[package]
name = "bio"
version = "0.1.0"
authors = ["George Roubos <cowkingdom@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "bio"
path = "src/lib.rs"
doctests = false

[dependencies]

[dev-dependencies]
cargo-husky = "1.5"
criterion = "0.3"

[[bench]]
name = "seq"
harness = false

[[bin]]
name = "dna"
path = "bin/dna.rs"
doctests = false
tests = false

[[bin]]
name = "rna"
path = "bin/rna.rs"
tests = false
doctests = false

[[bin]]
name = "revc"
path = "bin/revc.rs"
tests = false
doctests = false

[[bin]]
name = "fib"
path = "bin/fib.rs"
tests = false
doctests = false

[[bin]]
name = "iprb"
path = "bin/iprb.rs"
tests = false
doctests = false

[[bin]]
name = "gc"
path = "bin/gc.rs"
tests = false
doctests = false

[[bin]]
name = "grph"
path = "bin/grph.rs"
tests = false
doctests = false

[[bin]]
name = "prot"
path = "bin/prot.rs"
tests = false
doctests = false

[[bin]]
name = "ham"
path = "bin/ham.rs"
tests = false
doctests = false

[[bin]]
name = "subs"
path = "bin/subs.rs"
tests = false
doctests = false

[[bin]]
name = "revp"
path = "bin/revp.rs"
tests = false
doctests = false